### ISSUE TITLE
카드생성

### ISSUE THREAD

**Issue by ydh5017** [nbcamp-java5-yukssam/KanbanSSam#1]
## Description
카드 생성 API 구현 및 view 생성

## To-do
- [x] Card 엔티티 생성 및 작성
- [x] Card MVC 레이어 생성 및 작성
- [x] 카드 생성 기능 구현

## ETC
기타사항 없음
