### ISSUE TITLE
카드조회

### ISSUE THREAD

**Issue by ydh5017** [nbcamp-java5-yukssam/KanbanSSam#17]
## Description
카드 상세 조회 및 카드 목록 조회 기능 구현

## To-do
- [x] 카드 상세 조회 기능 구현
- [x] 카드 목록 조회 기능 구현
- [ ] 카드 목록 view 작성
- [ ] 카드 상세 view 작성

## ETC
기타사항 없음
