### ISSUE TITLE
카드 뷰 생성

### ISSUE THREAD

**Issue by ydh5017** [nbcamp-java5-yukssam/KanbanSSam#24]
## Description
카드 뷰 생성

## To-do
- [ ] 카드 수정 뷰 생성
- [ ] 카드 삭제 뷰 생성
- [ ] 카드 목록 뷰 생성
- [ ] 카드 상세 뷰 생성

## ETC
기타사항 없음
